version: 0.2

phases:
  pre_build:
    commands:
      - echo logging into Amazon ECR
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 003405557128.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image
      - docker build -t devops .
      - docker tag devops:latest 003405557128.dkr.ecr.us-east-1.amazonaws.com/devops:latest
  post_build:
    commands:
      - docker push 003405557128.dkr.ecr.us-east-1.amazonaws.com/devops:latest
artifacts:
  files:
    - imagedefinitions.json